In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

### train_test_split

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
shuffle_indexes = np.random.permutation(len(X))

In [9]:
shuffle_indexes

array([ 65,  45, 109,  18,  64,  20, 138,  76,  73,  98,  43,  21,  62,
       104,  82,  27, 134,  15, 146,  34,   6, 108,  89, 140,  10,  26,
        29,  69, 106, 132, 113,  60, 102, 128, 147, 117, 145, 105,  59,
        57, 120, 116, 142,  61, 127, 149, 141,  32, 137, 107,  11, 148,
        93, 114,  25,  91, 115, 125,  46,  84, 126,  41,  49,  48,   2,
        96,   9,   4,  16,  56, 136,  79,  47,  19, 133,   8,   1, 101,
       135, 144, 130,  30, 131,  85,  40,   7, 121,  52,  22, 122,  31,
        71,  35,  75,  83,   0,  28,  97,  90,  86,  54,  24, 100,  87,
        37,  58, 118, 143,  50,  33,  67,  70,  63, 110, 119,  42,  13,
        36,  92,  72,  99,  77,  95,  88,  23,  78,  55,  53, 111,  14,
        51, 124, 103, 129,  38,  80,  12,  17,  68,  66,  39,   3,  44,
       123,  81,  94,  74, 112, 139,   5])

In [10]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [11]:
test_size

30

In [12]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [13]:
X_train = X[test_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [16]:
print(X_train.shape)
print(y_train.shape)

(30, 4)
(120,)


In [17]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [18]:
from playML.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [20]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [21]:
from kNN.kNN import KNNClassifier

In [22]:
my_knn_clf = KNNClassifier(k=3)

In [23]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [24]:
y_predict = my_knn_clf.predict(X_test)

In [25]:
y_predict

array([0, 0, 2, 1, 1, 0, 0, 1, 0, 2, 0, 2, 2, 2, 1, 0, 1, 0, 2, 1, 0, 0, 1,
       0, 2, 2, 2, 0, 1, 2])

In [27]:
y_test

array([0, 0, 2, 1, 2, 0, 0, 1, 0, 2, 0, 2, 2, 2, 1, 0, 1, 0, 2, 1, 0, 0, 1,
       0, 2, 2, 2, 0, 1, 2])

In [28]:
 sum(y_predict == y_test)

29

In [29]:
 sum(y_predict == y_test)/len(y_test)

0.96666666666666667

### sklearn中的train_test_split

In [30]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [35]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [36]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
