# 其他创建numpy.array的方法

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [3]:
np.zeros(10).dtype

dtype('float64')

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.zeros((3, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [6]:
np.zeros(shape = (3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
np.ones((3, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
np.full(shape=(3,5), fill_value=666.6)

array([[ 666.6,  666.6,  666.6,  666.6,  666.6],
       [ 666.6,  666.6,  666.6,  666.6,  666.6],
       [ 666.6,  666.6,  666.6,  666.6,  666.6]])

# arange

In [13]:
[i for i in range(0 ,20 ,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [14]:
np.arange(0, 20 ,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.arange(0, 20 ,0.2)

array([  0. ,   0.2,   0.4,   0.6,   0.8,   1. ,   1.2,   1.4,   1.6,
         1.8,   2. ,   2.2,   2.4,   2.6,   2.8,   3. ,   3.2,   3.4,
         3.6,   3.8,   4. ,   4.2,   4.4,   4.6,   4.8,   5. ,   5.2,
         5.4,   5.6,   5.8,   6. ,   6.2,   6.4,   6.6,   6.8,   7. ,
         7.2,   7.4,   7.6,   7.8,   8. ,   8.2,   8.4,   8.6,   8.8,
         9. ,   9.2,   9.4,   9.6,   9.8,  10. ,  10.2,  10.4,  10.6,
        10.8,  11. ,  11.2,  11.4,  11.6,  11.8,  12. ,  12.2,  12.4,
        12.6,  12.8,  13. ,  13.2,  13.4,  13.6,  13.8,  14. ,  14.2,
        14.4,  14.6,  14.8,  15. ,  15.2,  15.4,  15.6,  15.8,  16. ,
        16.2,  16.4,  16.6,  16.8,  17. ,  17.2,  17.4,  17.6,  17.8,
        18. ,  18.2,  18.4,  18.6,  18.8,  19. ,  19.2,  19.4,  19.6,  19.8])

# linspace

In [17]:
np.linspace(0, 20, 10)

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

# random

In [18]:
np.random.randint(0,10)

6

In [19]:
np.random.randint(0,10,10)

array([9, 8, 0, 9, 3, 3, 8, 3, 0, 6])

In [20]:
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.random.randint(0,10, size=10)

array([5, 9, 1, 8, 7, 6, 8, 4, 1, 5])

In [22]:
np.random.randint(0,10, size=(3,5))

array([[0, 4, 9, 9, 5],
       [1, 0, 9, 4, 2],
       [3, 6, 7, 0, 5]])

In [24]:
np.random.seed(666)

In [25]:
np.random.randint(0,10, size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [26]:
np.random.randint(0,10, size=(3,5))

array([[4, 4, 0, 0, 4],
       [0, 4, 5, 7, 1],
       [0, 0, 6, 6, 0]])

In [27]:
np.random.seed(666)

In [28]:
np.random.randint(0,10, size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [29]:
np.random.random()

0.7315955468480113

In [30]:
np.random.random(10)

array([ 0.8578588 ,  0.76741234,  0.95323137,  0.29097383,  0.84778197,
        0.3497619 ,  0.92389692,  0.29489453,  0.52438061,  0.94253896])

In [31]:
np.random.random((3, 5))

array([[ 0.07473949,  0.27646251,  0.4675855 ,  0.31581532,  0.39016259],
       [ 0.26832981,  0.75366384,  0.66673747,  0.87287954,  0.52109719],
       [ 0.75020425,  0.32940234,  0.29130197,  0.00103619,  0.6361797 ]])

In [32]:
np.random.normal()

-1.5644858645303779

In [35]:
np.random.normal(10, 100)

-81.36003360756432

In [36]:
np.random.normal(0, 1, (3, 5))

array([[-0.27084407,  1.42024914, -0.98226439,  0.80976498,  1.85205227],
       [ 1.67819021, -0.98076924,  0.47031082,  0.18226991, -0.84388249],
       [ 0.20996833,  0.22958666,  0.26307642,  2.16633222, -1.04887593]])

In [37]:
np.random.normal(0,1.10)

-2.0324528652438296

In [38]:
np.random.normal(0,1,10)

array([ 0.53401503, -1.19574802, -0.28915737, -0.24332703, -0.74266653,
        1.20790511,  1.02787711,  0.0573882 , -1.56003976, -0.30401161])

In [39]:
np.random.normal?

In [40]:
np.random.normal(0,1,5)

array([-1.19843592, -0.87183499,  0.17659718, -0.20263364,  0.96702908])

In [41]:
np.random?

In [42]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap