In [1]:
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x = np.arange(15).reshape(3,5)

In [7]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
x.ndim

2

In [9]:
x.shape

(3, 5)

In [10]:
x.size

15

### numpy.array的数据访问

In [11]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
x[-1]

array([10, 11, 12, 13, 14])

In [13]:
x[0,0]

0

In [14]:
x[0,3]

3

In [17]:
x[2:4]

array([[10, 11, 12, 13, 14]])

In [18]:
x[0:4]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
x[::4]

array([[0, 1, 2, 3, 4]])

In [20]:
x[::3]

array([[0, 1, 2, 3, 4]])

In [21]:
x[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [22]:
x[:2,:4]

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [23]:
x[:2,:2]

array([[0, 1],
       [5, 6]])

In [24]:
x[:1,:4]

array([[0, 1, 2, 3]])

In [25]:
x[:3,:1]

array([[ 0],
       [ 5],
       [10]])

In [26]:
x[0,:]

array([0, 1, 2, 3, 4])

In [28]:
x[0,:].ndim

1

In [29]:
x[:,0]

array([ 0,  5, 10])

In [30]:
x[:,0].ndim

1

In [31]:
subX = x[:2, :3]

In [32]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [33]:
subX[0, 0] = 100

In [34]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [35]:
x

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [36]:
x[0,0] = 0

In [37]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [38]:
x


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
subX = x[:2, :3].copy()

In [41]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [42]:
subX[0,0] =100

In [43]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

### Reshape

In [45]:
x.shape

(3, 5)

In [46]:
x.ndim

2

In [54]:
y = np.ones(10)
y.reshape(2, 5)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [50]:
b = y.reshape(1,10)

In [51]:
b

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [52]:
y

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [55]:
y.shape

(10,)

In [57]:
y.reshape(10, -1)

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])