# 聚合操作

In [1]:
import numpy as np

L = np.random.random(100)

In [2]:
L

array([ 0.59714048,  0.41512516,  0.58707133,  0.18951584,  0.90309291,
        0.77204051,  0.28258794,  0.46535967,  0.71453208,  0.13118644,
        0.29126093,  0.16995056,  0.95811714,  0.70177821,  0.08504949,
        0.84578254,  0.70442718,  0.94899239,  0.06628329,  0.37959504,
        0.15653665,  0.0654534 ,  0.18790743,  0.85324959,  0.64997201,
        0.95550055,  0.59820204,  0.34618732,  0.08577774,  0.10077709,
        0.1001172 ,  0.87445404,  0.23210421,  0.80560864,  0.07362164,
        0.75244147,  0.71612073,  0.96299992,  0.88718959,  0.51991178,
        0.75859597,  0.39678405,  0.43717023,  0.29822248,  0.71392188,
        0.68370258,  0.00246802,  0.15173018,  0.77162259,  0.59887648,
        0.76277724,  0.68484162,  0.5974625 ,  0.67121683,  0.77113675,
        0.08687829,  0.42468954,  0.64080804,  0.78633878,  0.67564595,
        0.87454439,  0.53580947,  0.64850875,  0.49508298,  0.92429551,
        0.00560351,  0.04082684,  0.5224876 ,  0.39550643,  0.42

In [3]:
sum(L)

53.530009572615036

In [5]:
np.sum(L)

53.530009572615022

In [9]:
big_array = np.random.rand(1000000)
%timeit  sum(big_array)
%timeit  np.sum(big_array)

99.6 ms ± 345 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
406 µs ± 57.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
np.min(big_array)

2.5611624906440866e-06

In [11]:
np.max(big_array)

0.9999999534284929

In [12]:
big_array.min()

2.5611624906440866e-06

In [14]:
big_array.max()

0.9999999534284929

In [16]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
np.sum(X)

120

In [18]:
np.sum(X, axis=0)  #列求和

array([24, 28, 32, 36])

In [19]:
np.sum(X, axis=1) #行求和

array([ 6, 22, 38, 54])

In [21]:
np.prod(X)  #乘积

0

In [22]:
np.prod(X+1) #+1乘积

2004189184

In [23]:
np.mean(X) #求平均

7.5

In [24]:
np.median(X)  #求中位数

7.5

In [26]:
v = np.array([1,1,2,2,10])
np.mean(v)


3.2000000000000002

In [27]:
np.median(v)

2.0

In [28]:
np.percentile(big_array, q=50)

0.49978726755696262

In [29]:
np.median(big_array)

0.49978726755696262

In [30]:
np.percentile(big_array, q=100)

0.9999999534284929

In [31]:
np.max(big_array)

0.9999999534284929

In [35]:
for per in  [0,25,50,75,100]:
    print(np.percentile(big_array, q=per))  # 百分点分布情况

2.56116249064e-06
0.249551050127
0.499787267557
0.750492329258
0.999999953428


In [36]:
np.var(big_array)  #求方差

0.083403951794379996

In [37]:
np.std(big_array) #求标准差

0.28879742345523096

In [39]:
x = np.random.normal(0,1,size=1000000)

In [40]:
np.mean(x)

0.00022188779857032782

In [41]:
np.std(x) #求标准差

0.99923051384273776