In [1]:
import numpy as np


In [2]:
x = np.random.normal(0, 1, size=1000000)

In [3]:
np.mean(x)

-0.0014710942955960167

In [4]:
np.mean(x)

-0.0014710942955960167

### 索引

In [6]:
np.min(x)

-4.7249695928169659

In [7]:
np.argmin(x)

59478

In [8]:
x[59478]

-4.7249695928169659

In [10]:
np.argmax(x)

838637

In [12]:
x[838637]

5.399995584561136

In [13]:
np.max(x)

5.399995584561136

### 排序和使用索引


In [14]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
np.random.shuffle(x)

In [16]:
x

array([ 4, 11, 10, 13, 14,  7,  1,  2, 15,  8,  0,  9,  3,  5, 12,  6])

In [17]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
x.sort()

In [19]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
X = np.random.randint(10, size=(4,4))
X

array([[1, 3, 5, 0],
       [5, 0, 5, 1],
       [3, 6, 2, 2],
       [7, 1, 8, 4]])

In [21]:
np.sort(X)

array([[0, 1, 3, 5],
       [0, 1, 5, 5],
       [2, 2, 3, 6],
       [1, 4, 7, 8]])

In [22]:
np.sort(X, axis=1)

array([[0, 1, 3, 5],
       [0, 1, 5, 5],
       [2, 2, 3, 6],
       [1, 4, 7, 8]])

In [23]:
np.sort(X, axis=0)

array([[1, 0, 2, 0],
       [3, 1, 5, 1],
       [5, 3, 5, 2],
       [7, 6, 8, 4]])

In [25]:
X

array([[1, 3, 5, 0],
       [5, 0, 5, 1],
       [3, 6, 2, 2],
       [7, 1, 8, 4]])

In [26]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
np.random.shuffle(x)

In [28]:
x

array([15, 11,  7,  6, 13,  5, 12, 14,  0,  2, 10,  3,  4,  9,  8,  1])

In [29]:
np.argsort(x)

array([ 8, 15,  9, 11, 12,  5,  3,  2, 14, 13, 10,  1,  6,  4,  7,  0], dtype=int64)

In [30]:
np.partition(x, 3)

array([ 1,  0,  2,  3,  4,  5,  7,  8,  6,  9, 10, 11, 13, 12, 14, 15])

In [31]:
np.argpartition(x, 3)

array([15,  8,  9, 11, 12,  5,  2, 14,  3, 13, 10,  1,  4,  6,  7,  0], dtype=int64)

In [32]:
X

array([[1, 3, 5, 0],
       [5, 0, 5, 1],
       [3, 6, 2, 2],
       [7, 1, 8, 4]])

In [33]:
np.argsort(X, axis=1)

array([[3, 0, 1, 2],
       [1, 3, 0, 2],
       [2, 3, 0, 1],
       [1, 3, 0, 2]], dtype=int64)

In [34]:
np.argpartition(X, 2, axis=1)

array([[3, 0, 1, 2],
       [1, 3, 2, 0],
       [2, 3, 0, 1],
       [1, 3, 0, 2]], dtype=int64)

In [35]:
np.argpartition(X, 2, axis=0)

array([[0, 1, 2, 0],
       [2, 3, 1, 1],
       [1, 0, 0, 2],
       [3, 2, 3, 3]], dtype=int64)